MESSAGE_STATUS_ACCEPTED       = 'accepted'
MESSAGE_STATUS_QUEUED           = 'queued'
MESSAGE_STATUS_SENDING          = 'sending'
MESSAGE_STATUS_SENT             = 'sent'
MESSAGE_STATUS_RECEIVING        = 'receiving'
MESSAGE_STATUS_RECEIVED         = 'received'
MESSAGE_STATUS_DELIVERED         = 'delivered'
MESSAGE_STATUS_UNDELIVERED      = 'undelivered'
MESSAGE_STATUS_FAILED           = 'failed'
MESSAGE_STATUS_CHOICES = (
    (MESSAGE_STATUS_ACCEPTED, 'Accepted'),
    (MESSAGE_STATUS_QUEUED, 'Queued'),
    (MESSAGE_STATUS_SENDING, 'Sending'),
    (MESSAGE_STATUS_SENT, 'Sent'),
    (MESSAGE_STATUS_RECEIVING, 'Receiving'),
    (MESSAGE_STATUS_RECEIVED, 'Received'),
    (MESSAGE_STATUS_DELIVERED, 'Delivered'),
    (MESSAGE_STATUS_UNDELIVERED, 'Undelivered'),
    (MESSAGE_STATUS_FAILED, 'Failed'),
)
STATUS = [MESSAGE_STATUS_ACCEPTED ,
MESSAGE_STATUS_QUEUED  ,
MESSAGE_STATUS_SENDING  ,
MESSAGE_STATUS_SENT      ,
MESSAGE_STATUS_RECEIVING  ,
MESSAGE_STATUS_RECEIVED   ,
MESSAGE_STATUS_DELIVERED  ,
MESSAGE_STATUS_UNDELIVERED,
MESSAGE_STATUS_FAILED]
CITY_NKTT = 'Nouackott'
CITY_NBD = 'Nouadbou'
CITY_CHOICES = (
    (CITY_NBD, 'Nouadibou'),
    (CITY_NKTT, 'Nouackott'),
    )
